manager:
    resource: "@ManagerBundle/Controller"
    type: annotation

new_order:
    resource: "@NewOrderBundle/Controller"
    type: annotation

user_actions:
    resource: "@UserBundle/Controller"
    type: annotation
