parameters:
#    manager.example.class: IAgent\ManagerBundle\Example

services:
#    manager.example:
#        class: %manager.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
